export const surpriseMePrompts = [
  'koci kawałek słońca na tle deszczowego łuku',
  'robot-pirat wspinający się po piramidzie z ząbków morskich',
  'kosmiczna baśń z gwiazdami w roli głównej',
  'barwne ptaki na księżycowej huśtawce',
  'lew w koronie na ścieżce z gwiazdami',
  'słodki drapieżnik w świetle księżyca',
  'koty-piraci na wyspie z karmazynowymi żaglami',
  'podwodne miasto na dnie kielicha z ognistym mieczem',
  'szalona królowa na statku z bananowego słońca',
  'złap mnie, jeśli możesz, ale w kształcie góry',
  'miasto na końcu tęczy z bananowymi drzewami',
  'portret pana uwięzionego w ilustracji zmyślnego krajobrazu',
  'zegar z drzewem w deszczu na górze',
  'latająca radość nad wodą w południe',
  'błękitna róża w czerwcu z kocykiem',
  'król kwiatów na zielonym drzewie z gwiazdami',
  'magiczna mgła nad mlecznym oceanem',
  'psy na łące z koralikami w tle',
  'spacer z delfinem w wodzie o zmroku',
  'motyle na głowie w koronie',
  'wróżki z baśni na tle gwiazd',
  'bajeczna wróżka w raju z głębokim oceanem',
  'księżniczka na księżycu z bananami',
  'koty w kapeluszu na złotym brzegu',
  'góry na brzegu morza z bananem',
  'współczesny cyborg w pełni, ale w kształcie kota',
  'kwiat w butonierce na oknie w sztuce, ale zawsze dla bananów',
  'kot w oknie na całym świecie'
  ];